### ISSUE TITLE
Broken import with NumPy 1.26

### ISSUE THREAD

**Issue by lohedges** [conda-forge/deepmd-kit-feedstock#56]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Your input system relies on the `numpy.__config__.get_info` function, which isn't present in version 1.26. On import I get the following exception:

```python
from deepmd.infer import DeepPot
  File "/storage/home/vlc79/vlc79784/.conda/envs/mamba/lib/python3.10/site-packages/deepmd/__init__.py", line 32, in <module>
    set_mkl()
  File "/storage/home/vlc79/vlc79784/.conda/envs/mamba/lib/python3.10/site-packages/deepmd/env.py", line 244, in set_mkl
    if "mkl_rt" in np.__config__.get_info("blas_mkl_info").get("libraries", []):
AttributeError: module 'numpy.__config__' has no attribute 'get_info'
```

In an environment with NumPy 1.25:

```python
>>> import numpy
>>> numpy.__config__.get_info
<function get_info at 0x7fb91ccefec0>
```

With NumPy 1.26:

```python
>>> import numpy
>>> numpy.__config__.get_info
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'numpy.__config__' has no attribute 'get_info'
```

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by lohedges** [comment]
I can repost on your main development [repo](https://github.com/deepmodeling/deepmd-kit) if desired, but as it stands your current conda package is broken given the recipe used here.

**Comment by lohedges** [comment]
Many thanks for the quick fix, much appreciated.
